# root
GET http://localhost:1602/

###
# index
GET http://localhost:1602/api/v1/users

###
# create
POST http://localhost:1602/api/v1/users
Content-Type: application/json

{
    "id": 14,
    "name": "jancuk 14"
}

###
# show
GET http://localhost:1602/api/v1/users/14

###
PUT http://localhost:1602/api/v1/users/1
Content-Type: application/json

{
    "id": 1,
    "name": "paijo"
}

###
DELETE http://localhost:1602/api/v1/users/1


# PRODUCT ROUTE
###
GET http://localhost:1602/product

###
GET http://localhost:1602/product/1

###
POST http://localhost:1602/product
Content-Type: application/json

{
    "name": "Syifa Karim",
    "email": "syifa@email.com",
    "gender": "Female"
}

###
PATCH http://localhost:1602/product/1
Content-Type: application/json

{
    "name": "Aziz Zaind",
    "email": "admin@email.com",
    "gender": "Male"
}

###
DELETE http://localhost:1602/product/2